----Create table PostStatus
CREATE TABLE TB_POSTSTATUS
(
    STATUSID INTEGER PRIMARY KEY,
    STATUSNAME NVARCHAR2(255) NOT NULL UNIQUE
);
SELECT * FROM tb_poststatus;
CREATE SEQUENCE AUTO_INCREMENT_SEQUENCE_POSTSTATUS
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIGGER_AUTOINCRE_TB_POSTSTATUS_STATUSID
BEFORE INSERT ON
TB_POSTSTATUS
REFERENCING NEW AS NEW
    FOR EACH ROW BEGIN SELECT
    AUTO_INCREMENT_SEQUENCE_POSTSTATUS.NEXTVAL INTO :NEW.STATUSID
    FROM DUAL;
END;

INSERT INTO TB_POSTSTATUS (STATUSNAME) VALUES ('?ang ch? ');
INSERT INTO TB_POSTSTATUS (STATUSNAME) VALUES ('?ã có ng??i h?n');
INSERT INTO TB_POSTSTATUS (STATUSNAME) VALUES ('Thành công');
INSERT INTO TB_POSTSTATUS (STATUSNAME) VALUES ('?ã h?t h?n');
INSERT INTO TB_POSTSTATUS (STATUSNAME) VALUES ('?ã xóa');

----Create table Category
CREATE TABLE TB_CATEGORY
(
    CATEGORYID INTEGER PRIMARY KEY,
    CATEGORYNAME NVARCHAR2(255) NOT NULL UNIQUE
);
DROP SEQUENCE AUTO_INCREMENT_SEQUENCE_CATEGORY;
CREATE SEQUENCE AUTO_INCREMENT_SEQUENCE_CATEGORY
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIGGER_AUTOINCRE_TB_CATEGORY_CATEGORYID
BEFORE INSERT ON
TB_CATEGORY
REFERENCING NEW AS NEW
    FOR EACH ROW BEGIN SELECT
    AUTO_INCREMENT_SEQUENCE_CATEGORY.NEXTVAL INTO :NEW.CATEGORYID
    FROM DUAL;
END;

INSERT INTO TB_CATEGORY (CATEGORYNAME) VALUES ('Th?c ph?m');
INSERT INTO TB_CATEGORY (CATEGORYNAME) VALUES ('V?t d?ng');
INSERT INTO TB_CATEGORY (CATEGORYNAME) VALUES ('Y t?');
INSERT INTO TB_CATEGORY (CATEGORYNAME) VALUES ('Giáo d?c');
INSERT INTO TB_CATEGORY (CATEGORYNAME) VALUES ('B?a ?n');
INSERT INTO TB_CATEGORY (CATEGORYNAME) VALUES ('Khác');

----Create table Purpose
CREATE TABLE TB_PURPOSE
(
    PURPOSEID INTEGER PRIMARY KEY,
    PURPOSENAME NVARCHAR2(255) NOT NULL UNIQUE
);
DROP SEQUENCE AUTO_INCREMENT_SEQUENCE_PURPOSE;
CREATE SEQUENCE AUTO_INCREMENT_SEQUENCE_PURPOSE
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIGGER_AUTOINCRE_TB_PURPOSE_PURPOSEID
BEFORE INSERT ON
TB_PURPOSE
REFERENCING NEW AS NEW
    FOR EACH ROW BEGIN SELECT
    AUTO_INCREMENT_SEQUENCE_PURPOSE.NEXTVAL INTO :NEW.PURPOSEID
    FROM DUAL;
END;

INSERT INTO TB_PURPOSE (PURPOSENAME) VALUES ('Trao t?ng');
INSERT INTO TB_PURPOSE (PURPOSENAME) VALUES ('Xin nh?n');
INSERT INTO TB_PURPOSE (PURPOSENAME) VALUES ('Gây qu?');
INSERT INTO TB_PURPOSE (PURPOSENAME) VALUES ('Hi?n máu');
----Create table Role
CREATE TABLE TB_ROLE
(
    ROLEID INTEGER PRIMARY KEY,
    ROLENAME NVARCHAR2(255) NOT NULL
);
DROP SEQUENCE AUTO_INCREMENT_SEQUENCE_ROLE;
CREATE SEQUENCE AUTO_INCREMENT_SEQUENCE_ROLE
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIGGER_AUTOINCRE_TB_ROLE_ROLEID
BEFORE INSERT ON
TB_ROLE
REFERENCING NEW AS NEW
    FOR EACH ROW BEGIN SELECT
    AUTO_INCREMENT_SEQUENCE_ROLE.NEXTVAL INTO :NEW.ROLEID
    FROM DUAL;
END;

INSERT INTO TB_ROLE (ROLENAME) VALUES ('Ng??i dùng');
INSERT INTO TB_ROLE (ROLENAME) VALUES ('Qu?n tr? viên');
----Create table User
CREATE TABLE TB_USER
(
    USERID INTEGER PRIMARY KEY,
    FIRSTNAME NVARCHAR2(40) NOT NULL,
    LASTNAME NVARCHAR2(40) NOT NULL,
    GENDER INTEGER NOT NULL,
    PHONE CHAR(10) NOT NULL UNIQUE,
    DATEOFBIRTH DATE NOT NULL,
    EMAIL VARCHAR2(255) UNIQUE,
    SCORE INTEGER NOT NULL,
    AVATAR VARCHAR2(255),
    CREATEDON DATE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLEID INTEGER NOT NULL,
    ISDELETED INTEGER NOT NULL
);
DROP SEQUENCE AUTO_INCREMENT_SEQUENCE_USER;
--create sequence
CREATE SEQUENCE AUTO_INCREMENT_SEQUENCE_USER
START WITH 1
INCREMENT BY 1;
SELECT * FROM TB_USER;
CREATE OR REPLACE TRIGGER TRIGGER_AUTOINCRE_TB_USER_USERID
BEFORE INSERT ON
TB_USER
REFERENCING NEW AS NEW
    FOR EACH ROW BEGIN SELECT
    AUTO_INCREMENT_SEQUENCE_USER.NEXTVAL INTO :NEW.USERID
    FROM DUAL;
END;

--FOREIGN KEY OF TABLE TB_USER
alter table TB_USER 
add constraint FK_USER_ROLE foreign key (RoleId)
references TB_ROLE(Roleid);

INSERT INTO TB_USER (FIRSTNAME,LASTNAME,GENDER,PHONE,DATEOFBIRTH,EMAIL,SCORE,AVATAR,CREATEDON,PASSWORD,ROLEID,ISDELETED) VALUES  ('Nguy?n V?n', 'Nam', 1, '0375436543', TO_DATE('23/10/1998', 'dd/mm/yyyy'), 'nguyenvannam@gmail.com', 100, NULL, sysdate, '123456789', 2, 0);
INSERT INTO TB_USER (FIRSTNAME,LASTNAME,GENDER,PHONE,DATEOFBIRTH,EMAIL,SCORE,AVATAR,CREATEDON,PASSWORD,ROLEID,ISDELETED) VALUES  ('V? V?n ', 'H??ng', 1, '0586750123', TO_DATE('05/08/1996', 'dd/mm/yyyy'), 'vuvanhuong@gmail.com', 140, NULL, sysdate, '123455432', 1, 0);
INSERT INTO TB_USER (FIRSTNAME,LASTNAME,GENDER,PHONE,DATEOFBIRTH,EMAIL,SCORE,AVATAR,CREATEDON,PASSWORD,ROLEID,ISDELETED) VALUES  ('Ph?m Th? ', 'Xuân', 2, '0786542104', TO_DATE('15/06/1992', 'dd/mm/yyyy'), 'phamthixuan@gmail.com', 120, NULL, sysdate, '11223344', 1, 0);
INSERT INTO TB_USER (FIRSTNAME,LASTNAME,GENDER,PHONE,DATEOFBIRTH,EMAIL,SCORE,AVATAR,CREATEDON,PASSWORD,ROLEID,ISDELETED) VALUES  ('Nguy?n Tr?n Minh', 'Tú', 2, '0395040233', TO_DATE('12/03/2000', 'dd/mm/yyyy'), 'nguyentranminhtu@gmail.com', 80, NULL, sysdate, '20202021', 1, 0);
INSERT INTO TB_USER (FIRSTNAME,LASTNAME,GENDER,PHONE,DATEOFBIRTH,EMAIL,SCORE,AVATAR,CREATEDON,PASSWORD,ROLEID,ISDELETED) VALUES  ('D??ng Th? Thu', 'Trang', 2, '0776343252', TO_DATE('11/02/2002', 'dd/mm/yyyy'), 'dtthutrang@gmail.com', 200, NULL, sysdate, '20212022', 1, 0);
INSERT INTO TB_USER (FIRSTNAME,LASTNAME,GENDER,PHONE,DATEOFBIRTH,EMAIL,SCORE,AVATAR,CREATEDON,PASSWORD,ROLEID,ISDELETED) VALUES  ('Tr?n V? Nh?t ', 'Anh', 1, '0375889789', TO_DATE('25/12/1999', 'dd/mm/yyyy'), 'tranvnhatanh@gmail.com', 180, NULL, sysdate, 'anh123456', 1, 0);
INSERT INTO TB_USER (FIRSTNAME,LASTNAME,GENDER,PHONE,DATEOFBIRTH,EMAIL,SCORE,AVATAR,CREATEDON,PASSWORD,ROLEID,ISDELETED) VALUES  ('Nguy?n Hoàng ', 'Anh', 1, '0345768253', TO_DATE('31/03/1995', 'dd/mm/yyyy'), 'nguyenhoanganh@gmail.com', 150, NULL, sysdate, 'hoanganh@', 1, 0);
INSERT INTO TB_USER (FIRSTNAME,LASTNAME,GENDER,PHONE,DATEOFBIRTH,EMAIL,SCORE,AVATAR,CREATEDON,PASSWORD,ROLEID,ISDELETED) VALUES  ('Tr?n C?m', 'Thu', 2, '0342392222', TO_DATE('09/09/1997', 'dd/mm/yyyy'), 'trancamthu@gmail.com', 95, NULL, sysdate, 'camthu123@', 2, 0);
INSERT INTO TB_USER (FIRSTNAME,LASTNAME,GENDER,PHONE,DATEOFBIRTH,EMAIL,SCORE,AVATAR,CREATEDON,PASSWORD,ROLEID,ISDELETED) VALUES  ('Tr??ng Chí', 'C??ng', 1, '0933545218', TO_DATE('19/02/2001', 'dd/mm/yyyy'), 'truongchicuong@gmail.com', 105, NULL, sysdate, 'chicuong2022@', 2, 0);
INSERT INTO TB_USER (FIRSTNAME,LASTNAME,GENDER,PHONE,DATEOFBIRTH,EMAIL,SCORE,AVATAR,CREATEDON,PASSWORD,ROLEID,ISDELETED) VALUES  ('Nguy?n ??c ', '??i', 1, '0847523389', TO_DATE('25/10/1992', 'dd/mm/yyyy'), 'nguyenducdai@gmail.com', 125, NULL, sysdate, '135792468', 1, 0);
----Create table Post
CREATE TABLE TB_POST
(
    POSTID INTEGER PRIMARY KEY,
    OWNERID INTEGER NOT NULL,
    PARTNERID INTEGER,
    STATUSID INTEGER NOT NULL,
    TITLE NVARCHAR2(255) NOT NULL,
    CONTENT NVARCHAR2(255) NOT NULL,
    CATEGORYID INTEGER NOT NULL,
    IMAGEPATH VARCHAR2(255),
    CREATEDON DATE NOT NULL,
    UPDATEDON DATE,
    PURPOSEID INTEGER NOT NULL,
    ISDELETED INTEGER NOT NULL
);
DROP SEQUENCE AUTO_INCREMENT_SEQUENCE_USER_POST;
--create sequence
CREATE SEQUENCE AUTO_INCREMENT_SEQUENCE_POST
START WITH 1
INCREMENT BY 1;

--table post
CREATE OR REPLACE TRIGGER TRIGGER_AUTOINCRE_TB_POST_POSTID
BEFORE INSERT ON
TB_POST
REFERENCING NEW AS NEW
    FOR EACH ROW BEGIN SELECT
    AUTO_INCREMENT_SEQUENCE_POST.NEXTVAL INTO :NEW.POSTID
    FROM DUAL;
END;
DROP TRIGGER TRIGGER_AUTOINCRE_TB_POST_POSTID;

--FOREIGN KEY OF TABLE TB_POST
alter table TB_POST 
add constraint FK_POST_USER1 foreign key (OwnerId)
references TB_USER(UserId);

alter table TB_POST 
add constraint FK_POST_USER2 foreign key (PartnerID)
references TB_USER(UserId);

alter table TB_POST 
add constraint FK_POST_STATUS foreign key (StatusId)
references TB_PostStatus(StatusId);

alter table TB_POST 
add constraint FK_POST_CATEGORY foreign key (CategoryId)
references TB_CATEGORY(CategoryId);

alter table TB_POST 
add constraint FK_POST_PURPOSE foreign key (PurposeId)
references TB_PURPOSE(PurposeId);
select * from tb_post;
INSERT INTO TB_POST (OWNERID,PARTNERID,STATUSID,TITLE,CONTENT,CATEGORYID,IMAGEPATH,CREATEDON,UPDATEDON,PURPOSEID,ISDELETED) VALUES (
2,NULL, 1, 'D? m?t bao 50kg g?o', 'V? quê mà còn bao g?o ngon 50kg, ai c?n liên h? mình t?ng', 1, NULL, sysdate, NULL, 1, 0);
INSERT INTO TB_POST (OWNERID,PARTNERID,STATUSID,TITLE,CONTENT,CATEGORYID,IMAGEPATH,CREATEDON,UPDATEDON,PURPOSEID,ISDELETED) VALUES (
3, null, 1, 'C?n cho tr?ng', 'Gà nhà nuôi ?? tr?ng nhi?u ?n không h?t, ai ?n tr?ng mình cho', 1, NULL, sysdate, NULL, 1, 0);
INSERT INTO TB_POST (OWNERID,PARTNERID,STATUSID,TITLE,CONTENT,CATEGORYID,IMAGEPATH,CREATEDON,UPDATEDON,PURPOSEID,ISDELETED) VALUES (4, null, 1, 'Gây qu? h? tr? tr? em m? côi do covid', 'Q?y t? thi?n ABC gây qu? h? tr? tr? em m? côi do covid. D? ki?n h? tr? 100 tr?, giá tr? 200 tri?u. Ngày k?t thúc: 5/5/2022', 6, NULL, sysdate, NULL, 3, 0);
INSERT INTO TB_POST (OWNERID,PARTNERID,STATUSID,TITLE,CONTENT,CATEGORYID,IMAGEPATH,CREATEDON,UPDATEDON,PURPOSEID,ISDELETED) VALUES (2, null, 1, 'Xin sgk l?p 9', 'Em c?n xin sách giáo khoa l?p 9 cho em c?a em. Ai có cho em xin ?. Em c?m ?n.', 4, NULL, sysdate, NULL, 2, 0);
INSERT INTO TB_POST (OWNERID,PARTNERID,STATUSID,TITLE,CONTENT,CATEGORYID,IMAGEPATH,CREATEDON,UPDATEDON,PURPOSEID,ISDELETED) VALUES (5, null, 1, 'Cho rau s?ch', 'Rau v??n ai c?n qua c?t ?n tho?i mái', 1, NULL, sysdate, NULL, 1, 0);
INSERT INTO TB_POST (OWNERID,PARTNERID,STATUSID,TITLE,CONTENT,CATEGORYID,IMAGEPATH,CREATEDON,UPDATEDON,PURPOSEID,ISDELETED) VALUES (6, null, 1, 'T?ng vitamin C', 'Mình dc t?ng 1 l? vitaminC không xài ', 3, NULL, sysdate, NULL, 1, 0);
INSERT INTO TB_POST (OWNERID,PARTNERID,STATUSID,TITLE,CONTENT,CATEGORYID,IMAGEPATH,CREATEDON,UPDATEDON,PURPOSEID,ISDELETED) VALUES (6, null, 1, 'Xin s?a cho bé 5 tháng tu?i', 'V? ch?ng công nhân ?ang b? n? l??ng nên r?t khó kh?n, mong ???c cô chú anh ch? h? tr? ít s?a cho cháu.', 1, NULL, sysdate, NULL, 2, 0);
INSERT INTO TB_POST (OWNERID,PARTNERID,STATUSID,TITLE,CONTENT,CATEGORYID,IMAGEPATH,CREATEDON,UPDATEDON,PURPOSEID,ISDELETED) VALUES (7, null, 1, 'T?ng sách gi?i tích, v?t lí', 'Mình có d? sách gi?i tích 1 2, v?t lí 1 2, em nào c?n mình t?ng', 4, NULL, sysdate, NULL, 1, 0);
INSERT INTO TB_POST (OWNERID,PARTNERID,STATUSID,TITLE,CONTENT,CATEGORYID,IMAGEPATH,CREATEDON,UPDATEDON,PURPOSEID,ISDELETED) VALUES (4, null, 1, 'T?ng cà ri', 'Nay h?c n?u ?n, cà ri mình n?u ngon l?m, b?n nào qua ?n ph? mình mình c?m ?n', 5, NULL, sysdate, NULL, 1, 0);
INSERT INTO TB_POST (OWNERID,PARTNERID,STATUSID,TITLE,CONTENT,CATEGORYID,IMAGEPATH,CREATEDON,UPDATEDON,PURPOSEID,ISDELETED) VALUES (3, null, 1, 'Xin sách toeic', 'Có anh ch? nào h?c xong toeic thì cho em xin ho?c mua l?i ?', 4, NULL, sysdate, NULL, 2, 0);
-----FUNCTION---------
--1. CHECK LOGIN

--2. F_SUM_SCORE
--CREATE OR REPLACE FUNCTION F_SUM_SCORE(USER_ID INTEGER)
--RETURN INTEGER
--AS
--    TOTAL_SCORE INTEGER;
--BEGIN
--    SELECT SUM(SCORE) INTO TOTAL_SCORE
--    FROM TB_USER
--    WHERE USERID=USER_ID;
--RETURN TOTAL_SCORE;
--EXCEPTION WHEN NO_DATA_FOUND THEN
--RETURN ('NO DATA FOUND');
--END;
--
--SET SERVEROUTPUT ON;
--EXECUTE dbms_output.put_line('TOTAL SCORE IS: '||F_SUM_SCORE(&USER_ID));

--3.F_SUM_POST_OWNER
--CREATE OR REPLACE FUNCTION F_COUNT_POST_OWNER(OWNER_ID NUMBER)
--RETURN NUMBER
--AS
--    COUNT_POST_OWNER NUMBER;
--BEGIN
--    SELECT COUNT(OWNERID) INTO COUNT_POST_OWNER
--    FROM TB_POST
--    WHERE OWNERID=OWNER_ID;
--RETURN COUNT_POST_OWNER;
--EXCEPTION WHEN NO_DATA_FOUND THEN
--RETURN ('NO DATA FOUND');
--END;
--
--SET SERVEROUTPUT ON;
--EXECUTE dbms_output.put_line('THE NUMBERS OF POSTS IS: '||F_COUNT_POST_OWNER(&OWNER_ID));

--4.F_FIND_USER

CREATE OR REPLACE FUNCTION F_FIND_USER(USER_ID TB_USER.USERID%TYPE)
RETURN %type
AS
RETURN 
        SELECT * 
        FROM TB_USER
        WHERE USERID=USER_ID;
END;