CREATE TABLE TB_NOTIFICATION
(
    NOTIID INTEGER PRIMARY KEY,
    USERID INTEGER NOT NULL,
    POSTID INTEGER,
    CREATEON DATE NOT NULL,
    ISSEEN INTEGER NOT NULL
);

CREATE SEQUENCE AUTO_INCREMENT_SEQUENCE_NOTIFICATION
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIGGER_AUTOINCRE_TB_NOTIFICATION_NOTIID
BEFORE INSERT ON
TB_NOTIFICATION
REFERENCING NEW AS NEW
    FOR EACH ROW BEGIN SELECT
    AUTO_INCREMENT_SEQUENCE_NOTIFICATION.NEXTVAL INTO :NEW.CATEGORYID
    FROM DUAL;
END;

--FOREIGN KEY OF TABLE TB_NOTIFICATION
alter table TB_NOTIFICATION
add constraint FK_NOTIFICATION_USERID foreign key (UserId)
references TB_USER(UserId);

alter table TB_NOTIFICATION
add constraint FK_NOTIFICATION_POSTID foreign key (PostId)
references TB_POST(PostId);