----Create table PostStatus
CREATE TABLE TB_POSTSTATUS
(
    STATUSID INTEGER PRIMARY KEY,
    STATUSNAME NVARCHAR2(255) NOT NULL UNIQUE
);

CREATE SEQUENCE AUTO_INCREMENT_SEQUENCE_POSTSTATUS
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIGGER_AUTOINCRE_TB_POSTSTATUS_STATUSID
BEFORE INSERT ON
TB_POSTSTATUS
REFERENCING NEW AS NEW
    FOR EACH ROW BEGIN SELECT
    AUTO_INCREMENT_SEQUENCE_POSTSTATUS.NEXTVAL INTO :NEW.STATUSID
    FROM DUAL;
END;

INSERT INTO TB_POSTSTATUS (STATUSNAME) VALUES ('Đang chờ ');
INSERT INTO TB_POSTSTATUS (STATUSNAME) VALUES ('Đã có người hẹn');
INSERT INTO TB_POSTSTATUS (STATUSNAME) VALUES ('Thành công');
INSERT INTO TB_POSTSTATUS (STATUSNAME) VALUES ('Đã hết hạn');
INSERT INTO TB_POSTSTATUS (STATUSNAME) VALUES ('Đã xóa');

