/*
CREATE AUTO INCREMENT FOR PRIMARY KEY
*/
--create sequence
CREATE SEQUENCE AUTO_INCREMENT_SEQUENCE
START WITH 1111
INCREMENT BY 1;
/
--FORMAT NAME FOR SEQUENCE: TRIGGER_AUTOINCRE_name table_name attribute
--table user
CREATE OR REPLACE TRIGGER TRIGGER_AUTOINCRE_TB_USER_USERID
BEFORE INSERT ON
TB_USER
REFERENCING NEW AS NEW
    FOR EACH ROW BEGIN SELECT
    AUTO_INCREMENT_SEQUENCE.NEXTVAL INTO :NEW.USERID
    FROM DUAL;
END;
/
--tôi tạo thêm trigger này để lấy ngày tạo TÀI KHOẢN tự động nha
CREATE OR REPLACE TRIGGER TRIGGER_AUTOINCRE_TB_USER_CREATEDON
BEFORE INSERT ON
TB_USER
REFERENCING NEW AS NEW
    FOR EACH ROW BEGIN SELECT
    CURRENT_DATE INTO :NEW.CREATEDON
    FROM DUAL;
END;
/
--table post
CREATE OR REPLACE TRIGGER TRIGGER_AUTOINCRE_TB_POST_POSTID
BEFORE INSERT ON
TB_POST
REFERENCING NEW AS NEW
    FOR EACH ROW BEGIN SELECT
    AUTO_INCREMENT_SEQUENCE.NEXTVAL INTO :NEW.POSTID
    FROM DUAL;
END;
/
--tôi tạo thêm trigger này để lấy ngày tạo POST tự động
CREATE OR REPLACE TRIGGER TRIGGER_AUTOINCRE_TB_POST_CREATEDON
BEFORE INSERT ON
TB_POST
REFERENCING NEW AS NEW
    FOR EACH ROW BEGIN SELECT
    CURRENT_DATE INTO :NEW.CREATEDON
    FROM DUAL;
END;
/
--table category
CREATE OR REPLACE TRIGGER TRIGGER_AUTOINCRE_TB_CATEGORY_CATEGORYID
BEFORE INSERT ON
TB_CATEGORY
REFERENCING NEW AS NEW
    FOR EACH ROW BEGIN SELECT
    AUTO_INCREMENT_SEQUENCE.NEXTVAL INTO :NEW.CATEGORYID
    FROM DUAL;
END;
/
--table purpose
CREATE OR REPLACE TRIGGER TRIGGER_AUTOINCRE_TB_PURPOSE_PURPOSEID
BEFORE INSERT ON
TB_PURPOSE
REFERENCING NEW AS NEW
    FOR EACH ROW BEGIN SELECT
    AUTO_INCREMENT_SEQUENCE.NEXTVAL INTO :NEW.PURPOSEID
    FROM DUAL;
END;
/
--table role
CREATE OR REPLACE TRIGGER TRIGGER_AUTOINCRE_TB_ROLE_ROLEID
BEFORE INSERT ON
TB_ROLE
REFERENCING NEW AS NEW
    FOR EACH ROW BEGIN SELECT
    AUTO_INCREMENT_SEQUENCE.NEXTVAL INTO :NEW.ROLEID
    FROM DUAL;
END;
/
--table scoretransaction 
CREATE OR REPLACE TRIGGER TRIGGER_AUTOINCRE_TB_SCORETRANSACTION_SCORETRANSACTIONID
BEFORE INSERT ON
TB_SCORETRANSACTION
REFERENCING NEW AS NEW
    FOR EACH ROW BEGIN SELECT
    AUTO_INCREMENT_SEQUENCE.NEXTVAL INTO :NEW.SCORETRANSACTIONID
    FROM DUAL;
END;
/
--table poststatus
CREATE OR REPLACE TRIGGER TRIGGER_AUTOINCRE_TB_POSTSTATUS_STATUSID
BEFORE INSERT ON
TB_POSTSTATUS
REFERENCING NEW AS NEW
    FOR EACH ROW BEGIN SELECT
    AUTO_INCREMENT_SEQUENCE.NEXTVAL INTO :NEW.STATUSID
    FROM DUAL;
END;
/