/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Report;

import ConnectDB.OracleConnUtils;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Admin
 */
public class DemoChart extends javax.swing.JFrame {

    /**
     * Creates new form DemoChart
     */
    public DemoChart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton1)
                .addGap(63, 63, 63)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        DefaultPieDataset dataset = new DefaultPieDataset();
        try {
            Connection conn = (Connection) OracleConnUtils.getOracleConnection();
            
            
            Statement st1 = conn.createStatement();
            
             ResultSet rs = st1.executeQuery("select count(*) from tb_post where statusid = 3");
    rs.next();
    
    
     int count_success = rs.getInt("count(*)");
    dataset.setValue("Thành công", count_success);
    
    
    rs = st1.executeQuery("select count(*) from tb_post where statusid = 1");
    rs.next();
    
    int count_waiting = rs.getInt("count(*)");
    dataset.setValue("Đang chờ", count_waiting);
    
    
    rs = st1.executeQuery("select count(*) from tb_post where statusid = 2");
    rs.next();
    
    
    
    
     int count_scheduling = rs.getInt("count(*)");
    dataset.setValue("Đã có lịch hẹn", count_scheduling);
    
    
        } catch (SQLException ex) {
            Logger.getLogger(DemoChart.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DemoChart.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
        
        
         JFreeChart chart = ChartFactory.createPieChart("Biểu đồ tình trạng của bài viết",dataset, true,true, true);
        PiePlot p = (PiePlot)chart.getPlot();
        
        
        
        ChartFrame frame = new ChartFrame("Thống kê tình trạng bài viêt",chart);
frame.setVisible(true);
frame.setSize(450,500);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        DefaultPieDataset dataset = new DefaultPieDataset();
        try {
            Connection conn = (Connection) OracleConnUtils.getOracleConnection();
            
            Statement st1 = conn.createStatement();
            
             ResultSet rs = st1.executeQuery("select count(*) from tb_post where categoryid = 1");
    rs.next();
      int count_ThucPham = rs.getInt("count(*)");
    dataset.setValue("Thuc pham", count_ThucPham);
    
    
     rs = st1.executeQuery("select count(*) from tb_post where categoryid = 2");
    rs.next();
    
    
    
    
     int count_VatDung = rs.getInt("count(*)");
    dataset.setValue("Vat dung", count_VatDung);
    
    
    
    rs = st1.executeQuery("select count(*) from tb_post where categoryid = 3");
    rs.next();
    int count_curing = rs.getInt("count(*)");
    dataset.setValue("Y te", count_curing);
    
    
    
    
     rs = st1.executeQuery("select count(*) from tb_post where categoryid = 4");
    rs.next();
    int count_education = rs.getInt("count(*)");
    dataset.setValue("Giao duc", count_education);
    
    
    
        rs = st1.executeQuery("select count(*) from tb_post where categoryid = 5");
    rs.next();
    int count_meals = rs.getInt("count(*)");
    dataset.setValue("Bua an", count_meals);
    
    
    
          rs = st1.executeQuery("select count(*) from tb_post where categoryid = 6");
    rs.next();
    int count_khac = rs.getInt("count(*)");
    dataset.setValue("Khac", count_khac);
    
    
    
    
    
        } catch (SQLException ex) {
            Logger.getLogger(DemoChart.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DemoChart.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        JFreeChart chart = ChartFactory.createPieChart("Biểu đồ phân loại vật phẩm của bài viết",dataset, true,true, true);
        PiePlot p = (PiePlot)chart.getPlot();
        ChartFrame frame = new ChartFrame("Pie",chart);
frame.setVisible(true);
frame.setSize(450,500);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemoChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemoChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemoChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoChart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
