CREATE TABLE tb_city (
    cityid    INTEGER PRIMARY KEY,
    cityname  NVARCHAR2(255) NOT NULL
)
    
--create sequence

CREATE SEQUENCE auto_increment_sequence_city START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trigger_autoincre_tb_city_cityid BEFORE
    INSERT ON tb_city
    REFERENCING
        NEW AS new
    FOR EACH ROW
BEGIN
    SELECT
        auto_increment_sequence_city.NEXTVAL
    INTO :new.cityid
    FROM
        dual;

END;

INSERT INTO TB_CITY (CITYNAME) VALUES ('An Giang');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Bà Rịa - Vũng Tàu');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Bắc Giang');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Bắc Kạn');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Bạc Liêu');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Bắc Ninh');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Bến Tre');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Bình Định');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Bình Dương');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Bình Phước');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Bình Thuận');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Cà Mau');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Cần Thơ');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Cao Bằng');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Đà Nẵng');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Đắk Lắk');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Đắk Nông');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Điện Biên');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Đồng Nai');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Đồng Tháp');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Gia Lai');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Hà Giang');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Hà Nam');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Hà Nội');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Hà Tĩnh');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Hải Dương');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Hải Phòng');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Hậu Giang');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Hòa Bình');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Hưng Yên');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Khánh Hòa');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Kiên Giang');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Kon Tum');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Lai Châu');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Lâm Đồng');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Lạng Sơn');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Lào Cai');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Long An');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Nam Định');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Nghệ An');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Ninh Bình');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Ninh Thuận');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Phú Thọ');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Phú Yên');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Quảng Bình');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Quảng Nam');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Quảng Ngãi');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Quảng Ninh');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Quảng Trị');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Sóc Trăng');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Sơn La');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Tây Ninh');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Thái Bình');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Thái Nguyên');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Thanh Hóa');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Thừa Thiên Huế');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Tiền Giang');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Thành phố Hồ Chí Minh');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Trà Vinh');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Tuyên Quang');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Vĩnh Long');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Vĩnh Phúc');
INSERT INTO TB_CITY (CITYNAME) VALUES ('Yên Bái');