----Create table Purpose
CREATE TABLE TB_PURPOSE
(
    PURPOSEID INTEGER PRIMARY KEY,
    PURPOSENAME NVARCHAR2(255) NOT NULL UNIQUE
);
--Trigger tăng PURPOSEID tự động
CREATE SEQUENCE AUTO_INCREMENT_SEQUENCE_PURPOSE
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIGGER_AUTOINCRE_TB_PURPOSE_PURPOSEID
BEFORE INSERT ON
TB_PURPOSE
REFERENCING NEW AS NEW
    FOR EACH ROW BEGIN SELECT
    AUTO_INCREMENT_SEQUENCE_PURPOSE.NEXTVAL INTO :NEW.PURPOSEID
    FROM DUAL;
END;
--insert dữ liệu cho bảng
INSERT INTO TB_PURPOSE (PURPOSENAME) VALUES ('Trao tặng');
INSERT INTO TB_PURPOSE (PURPOSENAME) VALUES ('Xin nhận');
INSERT INTO TB_PURPOSE (PURPOSENAME) VALUES ('Gây quỹ');
INSERT INTO TB_PURPOSE (PURPOSENAME) VALUES ('Hiến máu');
commit;