/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.main;

import static Process.image.scaleImage;
import Process.post;
import static Process.postCategory.getCategoryNameFromId;
import static Process.postPurpose.getPurposeNameFromId;
import static Process.postStatus.getStatusNameFromId;
import Process.user;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author giahu
 */
public class chiTietBaiVietJPanel extends javax.swing.JPanel {

    post post01;

    private void loadData() {
        System.out.println("width of label is" + Integer.toString(labelImage.getHeight()));
        if (post01.getImagePath() != null) {
            scaleImage("C:\\Users\\giahu\\OneDrive\\Máy tính\\usecase.png", labelImage);
        }
        
        labelTitle.setText(post01.getTitle());
        labelContent.setText(post01.getContent());
        labelImage.setIcon(new ImageIcon(post01.getImagePath()));
        labelCreatedOn.setText(post01.getCreatedOn());
        String postPath = getPurposeNameFromId(post01.getPurposeId()) + " > " + getCategoryNameFromId(post01.getCategoryId());
        labelPath.setText(postPath);
        labelStatus.setText(getStatusNameFromId(post01.getStatusId()));
    }

    /**
     * Creates new form NewJPanel
     */
    public chiTietBaiVietJPanel(String postId) {
        initComponents();
        labelImage.setSize(220,220);
        post01 = new post(postId);
        //nếu người đăng bài cũng là người đang xem bài viết
        if (mainFrame.currentUser.getUserId().equals(post01.getOwnerId())) {
            //bài viết có người đặt hẹn mới có thể xác nhận hoàn thành
            if (post01.getStatusId() != "2") {

                btnConfirmSchedule.setVisible(false);
            }

            //không thể đặt hẹn cho chính mình
            btnSchedule.setVisible(false);

        } //người xem bài không phải người đăng bài
        else {
            //không thể xóa sửa bài viết
            btnDelete.setVisible(false);
            btnModify.setVisible(false);
            btnConfirmSchedule.setVisible(false);
            //bài viết không trống lịch hẹn thì không được đặt hẹn
            if (post01.getStatusId().equals("1") == false) {
                btnSchedule.setVisible(false);
            }
        }
        System.out.println("visible of btn delete is" + btnDelete.isVisible());

        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JPanel();
        labelPath = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        labelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        labelContent = new javax.swing.JTextArea();
        labelCreatedOn = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        labelImage = new javax.swing.JLabel();
        labelTitle1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnConfirmSchedule = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnSchedule = new javax.swing.JButton();

        heading.setBackground(new java.awt.Color(126, 186, 181));
        heading.setMinimumSize(new java.awt.Dimension(957, 56));
        heading.setPreferredSize(new java.awt.Dimension(953, 60));

        labelPath.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        labelPath.setForeground(new java.awt.Color(0, 51, 153));
        labelPath.setText("Đường dẫn");

        jButton12.setBackground(new java.awt.Color(255, 204, 204));
        jButton12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(51, 51, 51));
        jButton12.setIcon(new javax.swing.ImageIcon("C:\\Users\\giahu\\Downloads\\enter.png")); // NOI18N
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton12.setContentAreaFilled(false);
        jButton12.setHideActionText(true);
        jButton12.setOpaque(true);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headingLayout = new javax.swing.GroupLayout(heading);
        heading.setLayout(headingLayout);
        headingLayout.setHorizontalGroup(
            headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(labelPath, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headingLayout.setVerticalGroup(
            headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headingLayout.createSequentialGroup()
                        .addComponent(labelPath, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(199, 234, 227));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("NỘI DUNG");

        labelTitle.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(0, 51, 153));
        labelTitle.setText("TIÊU ĐỀ");

        labelContent.setEditable(false);
        labelContent.setColumns(20);
        labelContent.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        labelContent.setRows(5);
        labelContent.setText("test font");
        labelContent.setWrapStyleWord(true);
        labelContent.setOpaque(false);
        jScrollPane1.setViewportView(labelContent);

        labelCreatedOn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        labelCreatedOn.setForeground(new java.awt.Color(0, 51, 153));
        labelCreatedOn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCreatedOn.setText("NGÀY TẠO");

        labelStatus.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(0, 51, 153));
        labelStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelStatus.setText("TRẠNG THÁI");

        labelImage.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        labelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/images/size.png"))); // NOI18N
        labelImage.setToolTipText("");
        labelImage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        labelImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImageMouseClicked(evt);
            }
        });

        labelTitle1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        labelTitle1.setForeground(new java.awt.Color(0, 51, 153));
        labelTitle1.setText("TIÊU ĐỀ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(labelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(labelCreatedOn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(labelTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(540, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCreatedOn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 108, Short.MAX_VALUE)
                        .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(labelTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(408, Short.MAX_VALUE)))
        );

        jPanel5.setBackground(new java.awt.Color(126, 186, 181));
        jPanel5.setPreferredSize(new java.awt.Dimension(919, 60));
        jPanel5.setRequestFocusEnabled(false);

        btnConfirmSchedule.setBackground(new java.awt.Color(255, 230, 236));
        btnConfirmSchedule.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnConfirmSchedule.setForeground(new java.awt.Color(0, 51, 153));
        btnConfirmSchedule.setIcon(new javax.swing.ImageIcon("C:\\Users\\giahu\\Downloads\\girl.png")); // NOI18N
        btnConfirmSchedule.setText("Hoàn thành");
        btnConfirmSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmScheduleActionPerformed(evt);
            }
        });
        jPanel5.add(btnConfirmSchedule);

        btnDelete.setBackground(new java.awt.Color(255, 230, 236));
        btnDelete.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 51, 153));
        btnDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\giahu\\Downloads\\paper.png")); // NOI18N
        btnDelete.setText("XÓA BÀI VIẾT");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel5.add(btnDelete);

        btnModify.setBackground(new java.awt.Color(255, 230, 236));
        btnModify.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnModify.setForeground(new java.awt.Color(0, 51, 153));
        btnModify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/images/studying.png"))); // NOI18N
        btnModify.setText("SỬA BÀI VIẾT");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        jPanel5.add(btnModify);

        btnSchedule.setBackground(new java.awt.Color(255, 230, 236));
        btnSchedule.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnSchedule.setForeground(new java.awt.Color(0, 51, 153));
        btnSchedule.setIcon(new javax.swing.ImageIcon("C:\\Users\\giahu\\Downloads\\scheduling (1).png")); // NOI18N
        btnSchedule.setText("ĐẶT LỊCH HẸN");
        btnSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduleActionPerformed(evt);
            }
        });
        jPanel5.add(btnSchedule);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(heading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String[] options = {"Xóa", "Hủy"};
        int output = JOptionPane.showOptionDialog(this,
                "Bạn thực sự muốn xóa bài viết", "Xóa bài viết",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.YES_NO_OPTION, null, options, options[0]);
        if (output == JOptionPane.YES_OPTION) {
            try {
                post01.deletedPost();
            } catch (SQLException ex) {
                Logger.getLogger(chiTietBaiVietJPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(chiTietBaiVietJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            chuyenManHinhController.setView(new trangChuJPanel());
        } else if (output == JOptionPane.NO_OPTION) {
            System.out.println("No selected.");
        }


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnConfirmScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmScheduleActionPerformed

    }//GEN-LAST:event_btnConfirmScheduleActionPerformed

    private void btnScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduleActionPerformed
        String[] options = {"Xác nhận", "Hủy"};
        int output = JOptionPane.showOptionDialog(this,
                "Bạn muốn đặt hẹn với chủ bài viết?", "Đặt hẹn",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
        if (output == JOptionPane.YES_OPTION) {
            try {
                post01.schedulePost();
            } catch (SQLException ex) {
                Logger.getLogger(chiTietBaiVietJPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(chiTietBaiVietJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            new thongTinDatHen(new user(post01.getOwnerId())).setVisible(true);
        } else if (output == JOptionPane.NO_OPTION) {
            System.out.println("No selected.");
        }
    }//GEN-LAST:event_btnScheduleActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        String[] options = {"Xác nhận", "Hủy"};
        int output = JOptionPane.showOptionDialog(this,
                "Bạn muốn sửa bài viết này?", "Sửa bài viết",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
        if (output == JOptionPane.YES_OPTION) {
            //chuyển hướng sang trang sửa bài viết
            chuyenManHinhController.setView(new suaBaiVietJPanel(post01));
        } else if (output == JOptionPane.NO_OPTION) {
            System.out.println("No selected.");
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        chuyenManHinhController.setView(new trangChuJPanel());
    }//GEN-LAST:event_jButton12ActionPerformed

    private void labelImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImageMouseClicked
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        if (f != null) {
            System.out.println(f);
            scaleImage(f.toString(), labelImage);
        }
    }//GEN-LAST:event_labelImageMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmSchedule;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnSchedule;
    private javax.swing.JPanel heading;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea labelContent;
    private javax.swing.JLabel labelCreatedOn;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelPath;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTitle1;
    // End of variables declaration//GEN-END:variables
}
